# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path
---
name: Test

on:
   push:
     branches:
       - '*'

env:
  REGRESSION_TEST_PATH: ${{ format('{0}/{1}/', github.workspace, 'test') }}
  # TODO - Have to hard-code this for now since Actions don't yet allow the use of env here.
  LOGS_PATH: ${{ format('{0}/{1}', github.workspace, 'logs') }}
  DEPLOY_PATH: ${{ format('{0}/{1}/{2}/{3}', github.workspace, 'build', 'development', github.sha) }}

jobs:
  build: # job 1
    name: 'LDD Build'
    runs-on: ubuntu-latest
    if: github.actor != 'pdsen-ci'

    strategy:
      matrix:
        pds4_version: [ '1.14.0.0', '1.15.0.0' ]

        # include:
          # Example of including older version with LDDTool dev version
          # - pds4_version: '1.14.0.0'
          #   lddtool_development_release: True

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

      - name: Initialize workflow variables and cleanup
        id: vars
        shell: bash
        run: |
          if [[ "${{github.ref}}" == *"release"* ]]; then
            echo "FOOOOOOOO"
          fi
